language: go

go:
  - 1.11

env:
  - GO111MODULE=on

install:
  - go mod download
  - go install github.com/mitchellh/gox
  - curl -sL -o upx.txz https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
  - tar -xvf upx.txz

script:
  - go test ./...
  - gox -arch="amd64" -os="windows linux darwin"

after_success:
  - upx-3.94-amd64_linux/upx gossm_*

deploy:
  provider: releases
  api_key:
    secure: PEY0FFcnlSQXijoJEvYxSXFKYGI8DTnSw/FCeWzSCbESxInreSZmDDq9fQ10MXaU6xr/FFD+UOi9vKguFF9/9kXwWCvuDjwppigvWQXO6Kfz1NaTy/YqAowiye7XZ85mekaxh1ggpLilTZaU4hJBluE6vfnc42cXoV+szLYYVyZIP4QAstho/26lhICo9cdsPxYllKfdUkCM0o+q64wErWVJM/9N6WsrCmPEe1FbFWhsLafBP9dEA4n0F2mm5ge7MVdjLb3QrTA9Zs0++pR+vcaPJYxZo7bl8nrVmmXaGJlBZM0tYnxmvQuvboyD5YxkOZfagQFt+I7RF8UHE8HRveK7FBqUI7BlszcOkkn3MV4+hizxQk5RQxiCCelxPqNVofVvkvgxHYXfmiOPt8rQQbi+jrPk3UxQC3vE/fk3VhKDIPdxrp6/+G/C0ghsD1etp3ZpQtaj9c42qNBBlMllLwU7S0PcbdZuwUoD5XAf5bmwH96Dd6rnSYWr+nFiVbgdnC3kQ3a3kquxgwEVXHON5FCRcXKP3IjHdYWsCH6hG97goSwHCPTaDv+BeX8ByAB8n814AgOK99WvhoOYDa6MUIx4u3F1djv2a558WE2QVYTe0Ofh8vQ0SBGFIvODMwaDVYGTBIDUpkNEV8g9BouESzVfFKZpSHxRcuMo1jNpZI4=
  skip_cleanup: true
  file:
    - gossm_linux_amd64
    - gossm_darwin_amd64
    - gossm_windows_amd64.exe
  on:
    tags: true
    repo: glassechidna/gossm
